import Header from "@/components/header/Header";
import "./globals.css";

export const metadata = {
	title: "Loop Internet",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="body-background">
				<Header />
				<>{children}</>
			</body>
		</html>
	);
}
